version: "3"

services:
  kafka:
    build: ./docker/kafka-docker
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "log-event-stream-input:1:1,json-event-stream-output:1:1,si-simple-rules:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - bridge


  zookeeper:
    image: zookeeper
    tmpfs: "/datalog"
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
    networks:
      - bridge

networks:
  bridge: