---
flink:
  streamTimeCharacteristic: "ProcessingTime" # ProcessingTime|IngestionTime|EventTime
  job:
    groupId: "${spring.application.name}-group"
    name: "${spring.application.name}"
    parallelism: "1"

kafka:
  bootstrapServers: "localhost:9092"
  zookeeperConnect: "localhost:2181"
  events:
    sources:
      - topic: "json-event-stream-input"
        siddhiStreamName: "jsonInputStream"
        substreams:
          - streamName: "s3"
            type: "aws.S3"
        sink:
          topic: "json-event-stream-output"
          outputStreamName: "outputstream"
  rules:
    sources:
      - topic: "si-simple-rules" # Main topic/source name where rules control events are published
        controlStreamName: "simplerulesStream"
        mappingSourceDataStream : "${kafka.events.sources[0].siddhiStreamName}" #NOTE: This has to match with one of the kafka.events.sources.[x].siddhiStreamName
        subStreams:
          - streamName: "s3"
            type: "aws.s3"

spring:
  application:
    name: "SIFlinkJob"
...